version: "3"
services:
  app:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
      postgres_test:
        condition: service_healthy
    environment:
      # trust proxy settings - use true or ip address when proxied
      #TRUST_PROXY: "true"
      # node environment variable - switch to production for production environment
      NODE_ENV: development
      # postgres database variables
      CODING_EXAM_DB_HOST: postgres
      CODING_EXAM_DB_PORT: 5432
      CODING_EXAM_DB_NAME: coding_exam
      CODING_EXAM_DB_USER: coding_exam_user
      CODING_EXAM_DB_PASSWORD: coding_exam_pass
      # test postgres database variables
      CODING_EXAM_TESTDB_NAME: coding_exam_test
      CODING_EXAM_DB_TEST_USER: coding_exam_test_user
      CODING_EXAM_DB_TEST_PASSWORD: coding_exam_test_pass
      # canvas LTI variables
      CODING_EXAM_LTI_CLIENT_KEY: Codekey
      CODING_EXAM_LTI_CLIENT_SECRET: Keysecret
      # jwt variables
      CODING_EXAM_JWT_SECRET: JwtTokenSecret
      # openai variables
      CODING_EXAM_OPENAI_API_KEY: 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
    ports:
      - "9000:9000"
    #volumes:
      #- .:/app/
      #- /app/node_modules 

  postgres:
    container_name: postgres
    image: "postgres:12"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: coding_exam_user 
      POSTGRES_PASSWORD: coding_exam_pass
      POSTGRES_DB: coding_exam
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coding_exam_user -d coding_exam"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres_test:
    container_name: postgres_test
    image: "postgres:12"
    ports:
      - "6543:6543"
    environment:
      POSTGRES_USER: coding_exam_test_user
      POSTGRES_PASSWORD: coding_exam_test_pass
      POSTGRES_DB: coding_exam_test
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U coding_exam_test_user -d coding_exam_test"]
      interval: 10s
      timeout: 5s
      retries: 5