# Build Docker Workflow

# Workflow name
name: Build Docker

# Run only on pushes and pull requests on main branch, as well as tags
# https://docs.github.com/en/actions/using-workflows/triggering-a-workflow
on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

# Define a single job named build
jobs:
  build:
    # Run job on Ubuntu runner
    runs-on: ubuntu-latest

    # Job Steps
    steps:

      # Step 1 - Log In to GitHub Container Registry
      # https://github.com/docker/login-action
      - name: 1 - Login to GitHub Container Registry
        uses: docker/login-action@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Step 2 - Build and Push Docker Image
      # https://github.com/docker/build-push-action
      - name: 2 - Build and Push Docker Image
        uses: docker/build-push-action@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:latest

      # Step 3 - Make Release on GitHub
      # https://github.com/softprops/action-gh-release
      - name: 3 - Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          generate_release_notes: true